Repository Future-House/paper-qa, pull requests merged in 2024-12, with the labels that each got.

#738 Documenting why we don't handle evaluation failures in `GradablePaperQAEnvironment.step`
  paperqa/agents/task.py
Labels: documentation, size:XS, lgtm

#739 Refreshed test cassettes, fixed flaky test `test_search`, and fixed test type ignores
  tests/cassettes/TestLitQAEvaluation.test_from_question[didnt-match-and-llm-has-innate-knowledge].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[didnt-match-and-no-llm-innate-knowledge].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[empty-answer1].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[empty-answer2].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[empty-answer3].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[matched-correct-option].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[matched-incorrect-option].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[matched-several-options].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[matched-unsure-option].yaml
  tests/cassettes/TestLiteLLMModel.test_max_token_truncation[with-router].yaml
  tests/cassettes/TestLiteLLMModel.test_max_token_truncation[without-router].yaml
  tests/cassettes/TestLiteLLMModel.test_run_prompt[with-router].yaml
  tests/cassettes/TestLiteLLMModel.test_run_prompt[without-router].yaml
  tests/cassettes/TestTaskDataset.test_tool_failure.yaml
  tests/cassettes/test_arxiv_doi_is_used_when_available.yaml
  tests/cassettes/test_author_matching.yaml
  tests/cassettes/test_bad_dois.yaml
  tests/cassettes/test_bad_titles.yaml
  tests/cassettes/test_bulk_doi_search.yaml
  tests/cassettes/test_bulk_title_search.yaml
  tests/cassettes/test_crossref_journalquality_fields_filtering.yaml
  tests/cassettes/test_crossref_retraction_status.yaml
  tests/cassettes/test_docs_lifecycle.yaml
  tests/cassettes/test_doi_search[paper_attributes0].yaml
  tests/cassettes/test_doi_search[paper_attributes1].yaml
  tests/cassettes/test_doi_search[paper_attributes2].yaml
  tests/cassettes/test_ensure_sequential_run.yaml
  tests/cassettes/test_ensure_sequential_run_early_stop.yaml
  tests/cassettes/test_minimal_fields_filtering.yaml
  tests/cassettes/test_odd_client_requests.yaml
  tests/cassettes/test_partly_embedded_texts[False].yaml
  tests/cassettes/test_partly_embedded_texts[True].yaml
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
  tests/cassettes/test_s2_only_fields_filtering.yaml
  tests/cassettes/test_title_search[paper_attributes0].yaml
  tests/cassettes/test_title_search[paper_attributes1].yaml
  tests/cassettes/test_title_search[paper_attributes2].yaml
  tests/test_clients.py
Labels: bug, size:XS, lgtm

#725 Unpins pydantic >2.10.2 requirement, removes TYPE_CHECKING
  .pre-commit-config.yaml
  paperqa/settings.py
  pyproject.toml
  tests/test_agents.py
  uv.lock
Labels: size:S, lgtm

#717 Alternative maybe is text
  paperqa/docs.py
  paperqa/utils.py
  tests/test_paperqa.py
Labels: enhancement, size:S, lgtm

#741 Moved `README` to use `session` over `answer`
  README.md
Labels: bug, documentation, size:S, lgtm

#742 Moved `Docs.aadd` to support `str | os.PathLike`
  paperqa/docs.py
Labels: enhancement, size:XS, lgtm

#740 Cleared up 'Adding Documents Manually' docs
  README.md
Labels: documentation, size:S, lgtm

#743 Support env states with custom status functions
  paperqa/agents/tools.py
  tests/test_agents.py
Labels: enhancement, size:M, lgtm

#748 Moved JSON summary prompt to mention score is an integer
  paperqa/prompts.py
  paperqa/utils.py
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
  tests/test_paperqa.py
Labels: bug, enhancement, size:S, lgtm

#750 Created `dev` extra for convenience
  pyproject.toml
  uv.lock
Labels: enhancement, size:M, lgtm

#756 Populated `LICENSE`
  LICENSE
Labels: bug, size:XS

#752 Add partitioning func capabilities to allow doc-types-based embedding ranking
  paperqa/agents/tools.py
  paperqa/docs.py
  paperqa/llms.py
  tests/cassettes/test_partitioning_fn_docs[False].yaml
  tests/cassettes/test_partitioning_fn_docs[True].yaml
  tests/test_paperqa.py
Labels: enhancement, size:L, lgtm

#758 Exposed seeding of LitQA2 read and shuffling
  paperqa/agents/task.py
  paperqa/litqa.py
  tests/test_litqa.py
  tests/test_task.py
Labels: enhancement, size:M

#730 feat: Qdrant support
  .mailmap
  .pre-commit-config.yaml
  README.md
  paperqa/__init__.py
  paperqa/llms.py
  pyproject.toml
  tests/test_paperqa.py
  uv.lock
Labels: enhancement, size:L, lgtm

#762 Added answer an ideal to gradeable environments
  paperqa/agents/task.py
Labels: enhancement, size:S

#763 Pinned lower bound on `aiohttp` for `aiohttp.ClientConnectionResetError`
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: bug, size:XS

#766 Propagating citation count in flaky `test_pdf_reader_match_doc_details`
  tests/test_paperqa.py
Labels: bug, size:XS

#767 Renovate `lockFileMaintenance` respecting `schedule`, 2-week stability period, no `openai` pinning
  .github/renovate.json5
Labels: enhancement, size:S

#771 Added test split's source DOIs and question IDs
  docs/2024-10-16_litqa2-splits.json5
Labels: documentation, enhancement, size:XS

#772 Consolidated LDP imports into `ldp_shims` module
  paperqa/_ldp_shims.py
  paperqa/agents/main.py
  paperqa/agents/task.py
  paperqa/litqa.py
  paperqa/settings.py
Labels: enhancement, size:L

#774 Missing `None` failovers in LDP shims
  paperqa/_ldp_shims.py
Labels: bug, enhancement, size:S

#773 Dropping `refurb` in favor of its `ruff` port
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: enhancement, size:S, lgtm

#778 Converting `add_texts_and_embeddings` to async
  paperqa/docs.py
  paperqa/llms.py
Labels: enhancement, size:S
