Repository Future-House/paper-qa, pull requests merged in 2024-10, with the labels that each got.

#510 Refactor to create `settings.agent.index` grouping
  paperqa/agents/__init__.py
  paperqa/agents/main.py
  paperqa/agents/search.py
  paperqa/configs/contracrow.json
  paperqa/configs/wikicrow.json
  paperqa/settings.py
  tests/conftest.py
  tests/test_agents.py
  tests/test_cli.py
Labels: enhancement, size:L, lgtm

#513 Removed extra `save_index` calls, and added missing `changed`
  paperqa/agents/search.py
  tests/test_agents.py
Labels: bug, size:M, lgtm

#512 Not rebuilding `SearchIndex` every `paper_search`
  paperqa/agents/env.py
  paperqa/agents/main.py
  paperqa/agents/search.py
  paperqa/agents/tools.py
  tests/test_agents.py
Labels: enhancement, size:M, lgtm

#514 Updated citation to arxiv preprint
  CITATION.cff
  README.md
Labels: documentation, size:XS, lgtm

#515 Aviary agent `max_timesteps` and fixed `test_gather_evidence_rejects_empty_docs`
  paperqa/agents/main.py
  paperqa/agents/models.py
  paperqa/settings.py
  tests/test_agents.py
Labels: bug, enhancement, size:M, lgtm

#517 Moved `reset_log_levels` to `usefixtures`
  tests/conftest.py
  tests/test_agents.py
  tests/test_clients.py
Labels: enhancement, size:S, lgtm

#516 Decomposing `Answer.could_not_answer`
  paperqa/agents/main.py
  paperqa/agents/tools.py
  paperqa/types.py
  tests/test_paperqa.py
Labels: enhancement, size:S, lgtm

#518 Fixing `IndexSettings.use_absolute_paper_directory` leading to relative index file paths
  paperqa/agents/search.py
  paperqa/settings.py
  tests/test_agents.py
Labels: bug, size:L, lgtm

#519 Moving `run_ldp_agent` to center on `RolloutManager`
  .pre-commit-config.yaml
  paperqa/agents/main.py
  paperqa/agents/task.py
  paperqa/litqa.py
  pyproject.toml
  uv.lock
Labels: enhancement, size:M, lgtm

#522 Retrying on known Semantic Scholar flaky SSL error in `get_s2_doc_details_from_doi`
  paperqa/clients/crossref.py
  paperqa/clients/exceptions.py
  paperqa/clients/semantic_scholar.py
Labels: bug, size:M, lgtm

#523 Converted `PyMuPDF` message to warning logs
  paperqa/utils.py
Labels: bug, size:S, lgtm

#521 `rich.Progress` bar for monitoring index builds
  paperqa/agents/__init__.py
  paperqa/agents/search.py
Labels: enhancement, size:M, lgtm

#524 Better descriptions and log messages
  paperqa/agents/search.py
  paperqa/settings.py
Labels: enhancement, size:XS, lgtm

#526 Made it possible to skip chunking
  paperqa/configs/debug.json
  paperqa/docs.py
  paperqa/llms.py
  paperqa/readers.py
  paperqa/settings.py
  paperqa/types.py
  tests/test_paperqa.py
Labels: enhancement, size:L, lgtm

#529 Retrying on `aiohttp.ClientConnectionResetError`
  paperqa/clients/exceptions.py
  paperqa/utils.py
Labels: bug, documentation, size:S, lgtm

#520 Add rate limits for LLMs and Embedding Models
  README.md
  paperqa/configs/debug.json
  paperqa/configs/fast.json
  paperqa/configs/high_quality.json
  paperqa/configs/tier1_limits.json
  paperqa/configs/tier2_limits.json
  paperqa/configs/tier3_limits.json
  paperqa/configs/tier4_limits.json
  paperqa/configs/tier5_limits.json
  paperqa/core.py
  paperqa/llms.py
  paperqa/rate_limiter.py
  paperqa/settings.py
  pyproject.toml
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
  tests/test_agents.py
  tests/test_paperqa.py
  tests/test_rate_limiter.py
  uv.lock
Labels: enhancement, size:XXL, lgtm

#531 Disallowing confusing `None` from `IndexSettings.index_directory`, and `IndexSettings.get_named_index_directory`
  paperqa/agents/main.py
  paperqa/agents/search.py
  paperqa/settings.py
  tests/test_configs.py
Labels: enhancement, size:M, lgtm

#532 Add router_kwargs in separate control flow step
  paperqa/llms.py
  tests/test_configs.py
Labels: enhancement, size:S, lgtm

#533 Propagating `AgentSettings.agent_type` default for synchrony
  paperqa/agents/main.py
Labels: enhancement, size:XS, lgtm

#535 Adding retrying of `aembedding` if it fails
  paperqa/llms.py
Labels: bug, size:M, lgtm

#537 Add limits+coredis to mypy
  .pre-commit-config.yaml
  paperqa/rate_limiter.py
Labels: enhancement, size:M, lgtm

#540 Fixed yet another `api.semanticscholar.org:443 ssl:default` error via retrying
  paperqa/clients/semantic_scholar.py
  paperqa/utils.py
Labels: bug, size:M, lgtm

#544 Validating for broken index
  paperqa/agents/search.py
  tests/test_agents.py
  tests/test_task.py
Labels: bug, size:S, lgtm

#536 Added example how to use ollama hosted models
  README.md
Labels: documentation, size:M

#551 Making parsing resistant to failed inference of citations
  paperqa/docs.py
Labels: bug, size:S, lgtm

#552 Exposed log verbosity configuration function
  paperqa/agents/__init__.py
Labels: enhancement, size:S, lgtm

#554 Cleaned up log verbosity code
  paperqa/agents/__init__.py
Labels: enhancement, size:S, lgtm

#561 Refactoring `LiteLLMModel` before removing `Router`
  paperqa/llms.py
  tests/cassettes/TestLiteLLMModel.test_max_token_truncation.yaml
  tests/test_llms.py
  tests/test_paperqa.py
Labels: enhancement, size:M, lgtm

#555 Adds openalex client as a default client
  paperqa/clients/__init__.py
  paperqa/clients/crossref.py
  paperqa/clients/openalex.py
  paperqa/types.py
  paperqa/utils.py
  tests/cassettes/test_doi_search[paper_attributes0].yaml
  tests/cassettes/test_doi_search[paper_attributes1].yaml
  tests/cassettes/test_doi_search[paper_attributes2].yaml
  tests/cassettes/test_title_search[paper_attributes0].yaml
  tests/cassettes/test_title_search[paper_attributes1].yaml
  tests/cassettes/test_title_search[paper_attributes2].yaml
  tests/test_clients.py
  uv.lock
Labels: enhancement, size:L, lgtm

#564 Moving to `setup-uv` and `hynek/build-and-inspect-python-package` in CI
  .github/workflows/build.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  uv.lock
Labels: enhancement, size:M, lgtm

#566 Downloading `Package` artifact for `pypa/gh-action-pypi-publish`
  .github/workflows/build.yml
Labels: bug, size:XS, lgtm

#575 Fixing `Settings` propagation and always configuring LiteLLM retrying
  paperqa/agents/helpers.py
  paperqa/agents/main.py
  paperqa/agents/models.py
  paperqa/llms.py
Labels: bug, size:M, lgtm

#577 Fixing the ability to resume index builds
  paperqa/agents/search.py
  tests/test_agents.py
Labels: bug, size:M, lgtm

#578 Fixed `GLOBAL_RATE_LIMITER_TIMEOUT` env var typo
  paperqa/rate_limiter.py
Labels: bug, size:XS, lgtm

#587 Unsilencing manifest read failure when no CSV header is present
  paperqa/agents/search.py
  tests/test_agents.py
Labels: bug, size:M, lgtm

#585 Added `typeguard` to confirm type hints
  pyproject.toml
  uv.lock
Labels: enhancement, size:XS

#589 Renovate once/month, removing stale LiteLLM disables
  .github/renovate.json5
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: enhancement, size:S

#588 Fixed a few minor `SearchIndex` bugs and documented `SearchIndex`
  paperqa/agents/search.py
Labels: bug, documentation, enhancement, size:M, lgtm

#592 Limiting parsed page size to 1.28 million chars
  paperqa/docs.py
  paperqa/readers.py
  paperqa/settings.py
  tests/test_paperqa.py
Labels: bug, size:M, lgtm

#593 Stripping DOI URL prefix for `sources`
  paperqa/agents/task.py
  paperqa/types.py
Labels: bug, enhancement, size:S, lgtm

#594 Fix sequential client query clobbering
  paperqa/clients/__init__.py
  tests/cassettes/test_ensure_sequential_run.yaml
  tests/test_clients.py
Labels: bug, size:M, lgtm

#590 Add callback support in settings and tools
  paperqa/agents/tools.py
  paperqa/settings.py
  tests/test_agents.py
Labels: enhancement, size:L, lgtm

#595 Moved `validate_sources` to include all `sources` not found
  paperqa/agents/task.py
  tests/test_task.py
Labels: enhancement, size:S, lgtm

#598 Cleaning up citations
  CITATION.cff
  README.md
Labels: documentation, enhancement, size:M, lgtm

#600 Validating sources with case insensitive DOI matching
  paperqa/agents/task.py
Labels: bug, size:S, lgtm

#597 Cleaned and clarified deferred embeddings code
  paperqa/docs.py
  paperqa/types.py
  tests/cassettes/test_partly_embedded_texts.yaml
  tests/test_paperqa.py
Labels: bug, size:M, lgtm

#608 Fixed `NumpyVectorStore.clear` from not clearing `text_hashes`
  paperqa/llms.py
  tests/cassettes/test_docs_lifecycle.yaml
  tests/test_paperqa.py
Labels: bug, size:M, lgtm

#607 Moved Pydantic `model_config` to top of each class
  paperqa/agents/models.py
  paperqa/clients/__init__.py
  paperqa/clients/client_models.py
  paperqa/clients/unpaywall.py
  paperqa/settings.py
  paperqa/types.py
Labels: enhancement, size:S, lgtm

#610 Testing we can use `~` as `paper_directory`
  tests/test_cli.py
Labels: enhancement, size:M, lgtm

#606 Increased testing of `NumpyVectorStore` and `defer_embeddings`
  tests/cassettes/test_partly_embedded_texts.yaml
  tests/cassettes/test_partly_embedded_texts[False].yaml
  tests/cassettes/test_partly_embedded_texts[True].yaml
  tests/test_paperqa.py
Labels: enhancement, size:M, lgtm

#611 Expose env class to run_agent functions
  paperqa/agents/main.py
Labels: enhancement, size:XS, lgtm

#612 Exposed `LDPRolloutCallback` and `on_agent_action_callback` for `fake` agent
  paperqa/agents/main.py
Labels: enhancement, size:M, lgtm

#613 Fixed `NumpyVectorStore.__eq__`'s `NotImplemented` case
  paperqa/llms.py
  tests/test_paperqa.py
Labels: bug, size:M, lgtm

#614 Implemented `__deepcopy__` on all `Environment`s
  paperqa/agents/env.py
  paperqa/agents/task.py
  paperqa/litqa.py
  paperqa/llms.py
  tests/test_agents.py
  tests/test_paperqa.py
Labels: documentation, enhancement, size:L, lgtm

#615 Made embedding default
  paperqa/settings.py
Labels: size:XS, lgtm

#618 Pulled in latest PyMuPDF for `set_messages`
  paperqa/utils.py
  pyproject.toml
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
  tests/test_paperqa.py
  uv.lock
Labels: enhancement, size:S, lgtm

#619 Fixed crash due to DOI being a `list`
  paperqa/types.py
Labels: bug, size:S, lgtm

#620 Added configuration to adjust how contexts are displayed
  paperqa/docs.py
  paperqa/prompts.py
  paperqa/settings.py
  tests/test_configs.py
  tests/test_paperqa.py
Labels: enhancement, size:L, lgtm

#625 Fixing CI by regenerating `test_pdf_reader_match_doc_details` cassette
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
Labels: bug, size:XS

#626 Retrying flaky test `test_propagate_options`
  tests/test_agents.py
Labels: bug, size:XS, lgtm

#622 Regression protection in `embedding_model_factory`
  tests/test_agents.py
Labels: enhancement, size:S, lgtm

#628 Added `writer.wait_merging_threads` call
  paperqa/agents/search.py
Labels: enhancement, size:XS, lgtm

#627 Caching opened `tantivy.Index`es in the package
  paperqa/agents/search.py
  tests/test_agents.py
Labels: bug, enhancement, size:L, lgtm

#629 Printing the `text` in a failed `llm_parse_json`
  paperqa/core.py
Labels: bug, size:S, lgtm

#632 Change S2 client logic to use arxiv doi if it's defined
  paperqa/clients/semantic_scholar.py
  tests/cassettes/test_arxiv_doi_is_used_when_available.yaml
  tests/test_clients.py
Labels: enhancement, size:S, lgtm

#639 Increased retry count for `ClientConnectorDNSError` errors
  paperqa/clients/crossref.py
  paperqa/clients/semantic_scholar.py
Labels: bug, size:XS, lgtm

#640 Make string similarity case insensitive by default
  paperqa/utils.py
  tests/test_paperqa.py
Labels: enhancement, size:S, lgtm

#647 Pulling in latest `fhaviary`, `mypy`, `ruff`
  .github/renovate.json5
  .pre-commit-config.yaml
  paperqa/agents/env.py
  paperqa/agents/main.py
  paperqa/agents/search.py
  paperqa/agents/task.py
  paperqa/clients/semantic_scholar.py
  paperqa/llms.py
  paperqa/rate_limiter.py
  paperqa/readers.py
  paperqa/settings.py
  paperqa/types.py
  pyproject.toml
  tests/test_agents.py
  tests/test_clients.py
  uv.lock
Labels: enhancement, size:L, lgtm

#649 Add an after model validator ensuring temp=1 for o1 models
  paperqa/settings.py
  tests/test_configs.py
Labels: enhancement, size:S, lgtm

#650 Fixing crash due to `None` author
  paperqa/types.py
Labels: bug, size:XS, lgtm

#652 Fixing flaky tests `test_code` and `test_minimal_fields_filtering`
  tests/test_clients.py
  tests/test_paperqa.py
Labels: bug, size:M, lgtm

#653 Renamed to PQASession type
  paperqa/__init__.py
  paperqa/agents/env.py
  paperqa/agents/helpers.py
  paperqa/agents/main.py
  paperqa/agents/models.py
  paperqa/agents/task.py
  paperqa/agents/tools.py
  paperqa/docs.py
  paperqa/litqa.py
  paperqa/settings.py
  paperqa/types.py
  tests/conftest.py
  tests/test_agents.py
  tests/test_cli.py
  tests/test_paperqa.py
Labels: size:L, lgtm
