Repository Future-House/paper-qa, pull requests merged in 2024-09, with the labels that each got.

#316 Moving to `uv` for installation/CI, parallel `pre-commit` in CI
  .github/workflows/build.yml
  .github/workflows/tests.yml
  .gitignore
  .pre-commit-config.yaml
  .python-version
  paperqa/agents/__init__.py
  paperqa/agents/main.py
  paperqa/agents/models.py
  paperqa/config.py
  paperqa/types.py
  paperqa/utils.py
  pyproject.toml
  uv.lock
Labels: enhancement

#318 Fixing `pybtex` import by requiring `setuptools`
  pyproject.toml
  uv.lock
Labels: bug

#319 Fixing test installation in CI by specifying missing dependencies
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: bug

#324 Fixing `LLMModel.axyz_iter` type hints
  paperqa/llms.py
  tests/test_paperqa.py
Labels: enhancement

#330 `black`ened code to prevent IDE scrolling
  paperqa/agents/__init__.py
  paperqa/agents/helpers.py
  paperqa/agents/main.py
  paperqa/agents/models.py
  paperqa/agents/search.py
  paperqa/agents/tools.py
  paperqa/clients/client_models.py
  paperqa/clients/crossref.py
  paperqa/clients/semantic_scholar.py
  paperqa/clients/unpaywall.py
  paperqa/contrib/zotero.py
  paperqa/docs.py
  paperqa/llms.py
  paperqa/prompts.py
  paperqa/settings.py
  paperqa/types.py
  tests/test_agents.py
  tests/test_clients.py
  tests/test_paperqa.py
Labels: enhancement

#331 Optimized import paths
  paperqa/__init__.py
  paperqa/agents/__init__.py
  paperqa/agents/helpers.py
  paperqa/agents/main.py
  paperqa/agents/models.py
  paperqa/agents/search.py
  paperqa/agents/tools.py
  paperqa/clients/__init__.py
  paperqa/clients/client_models.py
  paperqa/clients/crossref.py
  paperqa/clients/journal_quality.py
  paperqa/clients/semantic_scholar.py
  paperqa/clients/unpaywall.py
  paperqa/contrib/zotero.py
  paperqa/core.py
  paperqa/docs.py
  paperqa/llms.py
  paperqa/readers.py
  paperqa/settings.py
  paperqa/types.py
  pyproject.toml
  uv.lock
Labels: enhancement

#328 Removed `pytest-mock` plugin
  pyproject.toml
  tests/test_configs.py
  uv.lock
Labels: enhancement

#329 Adding `pytest-xdist` plugin
  .github/workflows/tests.yml
  pyproject.toml
  uv.lock
Labels: enhancement

#332 Passing `mypy`
  .pre-commit-config.yaml
  paperqa/agents/__init__.py
  paperqa/agents/main.py
  paperqa/agents/search.py
  paperqa/readers.py
  paperqa/settings.py
  pyproject.toml
  tests/test_agents.py
Labels: bug

#333 Adding `refurb` tool, and `lint` CI
  .github/workflows/tests.yml
  paperqa/agents/__init__.py
  paperqa/agents/main.py
  paperqa/agents/models.py
  paperqa/agents/search.py
  paperqa/agents/tools.py
  paperqa/clients/crossref.py
  paperqa/contrib/zotero.py
  paperqa/docs.py
  paperqa/readers.py
  paperqa/settings.py
  paperqa/types.py
  paperqa/utils.py
  pyproject.toml
  tests/conftest.py
  tests/test_agents.py
  tests/test_paperqa.py
  uv.lock
Labels: enhancement

#334 Fixing arg ordering after #325
  paperqa/docs.py
  paperqa/llms.py
Labels: bug

#335 Fixing `parse_text` after #332
  paperqa/readers.py
Labels: bug

#338 Fixing union attr error
  tests/test_clients.py
Labels: bug

#340 Fixing two more tests
  tests/test_paperqa.py
Labels: bug

#341 All Ruff `ANN` autofixes
  paperqa/agents/__init__.py
  paperqa/agents/models.py
  paperqa/agents/search.py
  paperqa/clients/exceptions.py
  paperqa/docs.py
  paperqa/llms.py
  paperqa/types.py
  tests/conftest.py
  tests/test_agents.py
  tests/test_cli.py
  tests/test_clients.py
  tests/test_configs.py
  tests/test_paperqa.py
Labels: enhancement

#342 Adding in `.mailmap`
  .mailmap
  .pre-commit-config.yaml
Labels: enhancement

#343 Removed `LangchainVectorStore`, `llms` extra, and fixing up `README`
  README.md
  paperqa/__init__.py
  paperqa/llms.py
  pyproject.toml
  tests/test_paperqa.py
  uv.lock
Labels: bug

#346 Dropping `requests` dependency
  .pre-commit-config.yaml
  pyproject.toml
  tests/test_paperqa.py
  uv.lock
Labels: enhancement

#347 Removed `html2text` requirement
  paperqa/contrib/zotero.py
  paperqa/readers.py
  pyproject.toml
  uv.lock
Labels: enhancement

#348 Requiring Python 3.11+
  .github/workflows/tests.yml
  paperqa/agents/main.py
  paperqa/agents/models.py
  paperqa/agents/search.py
  paperqa/clients/client_models.py
  paperqa/llms.py
  paperqa/settings.py
  paperqa/utils.py
  pyproject.toml
  uv.lock
Labels: enhancement

#351 Better control flow in `litellm_get_search_query`
  paperqa/agents/helpers.py
Labels: enhancement

#354 Cleaning up dependencies
  .pre-commit-config.yaml
  paperqa/agents/models.py
  paperqa/readers.py
  pyproject.toml
  uv.lock
Labels: enhancement

#358 `aviary` and `ldp` for agents over `langchain`
  .pre-commit-config.yaml
  paperqa/agents/env.py
  paperqa/agents/main.py
  paperqa/agents/models.py
  paperqa/agents/search.py
  paperqa/agents/tools.py
  paperqa/configs/contracrow.json
  paperqa/configs/wikicrow.json
  paperqa/settings.py
  pyproject.toml
  tests/conftest.py
  tests/test_agents.py
  tests/test_clients.py
  tests/test_paperqa.py
  uv.lock
Labels: enhancement

#349 Adding `pylint`
  .github/workflows/tests.yml
  paperqa/agents/__init__.py
  paperqa/agents/main.py
  paperqa/agents/search.py
  paperqa/clients/__init__.py
  paperqa/contrib/zotero.py
  paperqa/core.py
  paperqa/llms.py
  paperqa/settings.py
  pyproject.toml
  uv.lock
Labels: enhancement

#367 README adjustments
  README.md
Labels: documentation

#369 Removed `StrPath` in favor of direct type hints
  paperqa/contrib/zotero.py
  paperqa/utils.py
Labels: enhancement

#373 Retrying if `ToolSelector` fails to select a tool
  .pre-commit-config.yaml
  paperqa/agents/main.py
  pyproject.toml
  uv.lock
Labels: bug

#379 Fix examples in README
  README.md
Labels: documentation

#383 Validating `LiteLLMModel.config` structure
  paperqa/llms.py
Labels: bug, size:S, lgtm

#384 No google auth, better CI names
  .github/workflows/build.yml
  .github/workflows/tests.yml
Labels: bug, size:XS, lgtm

#385 Fixing Pydantic validation in Python<3.12
  .github/workflows/tests.yml
  paperqa/llms.py
Labels: bug, size:S, lgtm

#386 LitQA2 downloading and question creation functionality
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  paperqa/litqa.py
  paperqa/prompts.py
  paperqa/settings.py
  pyproject.toml
  tests/test_litqa.py
  tests/test_paperqa.py
  uv.lock
Labels: enhancement, size:L, lgtm

#375 Testing `MemoryAgent` and timeouts on ldp agents
  paperqa/agents/main.py
  paperqa/agents/tools.py
  paperqa/utils.py
  tests/test_agents.py
Labels: enhancement, size:L, lgtm

#389 Fixing crash in `chunk_text` for empty file
  paperqa/agents/search.py
  paperqa/readers.py
  tests/stub_data/empty.txt
  tests/test_agents.py
  tests/test_paperqa.py
Labels: bug, size:M, lgtm

#398 Adding Renovate config and newer dependencies
  .github/renovate.json5
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: enhancement, size:S, lgtm

#400 Fixing mutable `BaseModel` defaults and removing extra `BaseModel`
  paperqa/agents/main.py
  paperqa/agents/models.py
  paperqa/docs.py
  paperqa/types.py
Labels: bug, size:M, lgtm

#405 Passing `mypy paperqa`
  pyproject.toml
Labels: bug, enhancement, size:XS, lgtm

#404 Adding `CONTRIBUTING.md`
  CONTRIBUTING.md
  README.md
Labels: documentation, size:M, lgtm

#401 Creating `LitQAv2TaskDataset` for agent training/evaluation
  paperqa/agents/env.py
  paperqa/agents/main.py
  paperqa/agents/task.py
  tests/test_task.py
Labels: enhancement, size:L, lgtm

#414 `DocMetadataClient` can now take instantiated providers and processors
  paperqa/clients/__init__.py
  paperqa/clients/retractions.py
  tests/stub_data/stub_retractions.csv
  tests/test_clients.py
Labels: size:M, lgtm

#407 Promoting agent factories to `Settings`
  paperqa/agents/main.py
  paperqa/settings.py
Labels: enhancement, size:L, lgtm

#420 Add stub_data_dir fixture to retraction test
  tests/cassettes/test_crossref_retraction_status.yaml
  tests/test_clients.py
Labels: bug, size:M, lgtm

#411 Broken title search ut
  paperqa/types.py
  tests/cassettes/test_title_search[paper_attributes0].yaml
  tests/cassettes/test_title_search[paper_attributes1].yaml
  tests/cassettes/test_title_search[paper_attributes2].yaml
  tests/test_clients.py
Labels: bug, size:L, lgtm

#424 Pinning min `pymupdf` version
  pyproject.toml
  uv.lock
Labels: bug, size:XS, lgtm

#425 Preventing `Environment`s from sharing one `Docs`
  paperqa/agents/task.py
  tests/test_task.py
Labels: enhancement, size:S, lgtm

#426 Dropped `PyCryptodome` and `build` dependencies
  .github/workflows/build.yml
  pyproject.toml
  tests/test_agents.py
  uv.lock
Labels: enhancement, size:S, lgtm

#430 `build_index` with defaults
  paperqa/agents/__init__.py
Labels: enhancement, size:S, lgtm

#431 Less common `CROSSREF_XYZ` warnings
  paperqa/clients/crossref.py
Labels: enhancement, size:M, lgtm

#432 DRY'd up default `indexes` default location
  paperqa/agents/main.py
  paperqa/agents/search.py
Labels: enhancement, size:XS, lgtm

#435 Including paper and evidence counts in metrics
  paperqa/agents/task.py
  tests/test_task.py
Labels: enhancement, size:M, lgtm

#437 Allowing case insensitive `"fake"` agent type
  paperqa/agents/main.py
  tests/test_agents.py
Labels: enhancement, size:S, lgtm

#438 Many documentation improvements
  .pre-commit-config.yaml
  README.md
Labels: documentation, size:L, lgtm

#439 Avoiding div0 crash in `LitQATaskDataset.compute_trajectory_metrics`
  paperqa/agents/task.py
  tests/test_task.py
Labels: bug, size:M, lgtm

#440 Added some docs and adjusted field names for ease of use in DocDetails
  README.md
  paperqa/clients/unpaywall.py
  paperqa/types.py
Labels: documentation, size:M, lgtm

#447 Fixing flaky test `test_pdf_reader_match_doc_details`
  paperqa/agents/search.py
  tests/test_paperqa.py
Labels: bug, documentation, size:M, lgtm

#444 Retrying Crossref's `aiohttp.ClientConnectorError`
  paperqa/clients/crossref.py
Labels: bug, size:M, lgtm

#445 Handling `AttributeError` on structured citation prompt failure
  paperqa/docs.py
Labels: bug, size:S, lgtm

#448 Documenting and cleaning up manifest file logic
  README.md
  paperqa/agents/search.py
  paperqa/settings.py
Labels: documentation, enhancement, size:M, lgtm

#463 Latest dependencies for `pylint` 3.3
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: enhancement, size:XS

#466 Down-pinning `openai` 1.47 since it breaks CI
  pyproject.toml
  uv.lock
Labels: bug, size:XS, lgtm

#468 chore: add .gitattributes for cassettes file
  .gitattributes
Labels: size:XS, lgtm

#465 Fixing flaky `test_tool_failure`
  tests/cassettes/TestTaskDataset.test_tool_failure.yaml
  tests/conftest.py
  tests/test_task.py
Labels: bug, size:S, lgtm

#469 Documenting manifest CSV pathing a bit more
  paperqa/agents/search.py
  paperqa/settings.py
Labels: documentation, size:M, lgtm

#472 Handling S2 `KeyError` crash during indexing
  paperqa/clients/semantic_scholar.py
Labels: bug, size:S, lgtm

#474 Fixing `pymupdf.mupdf.FzErrorFormat` crash by recasting as an `ImpossibleParsingError`
  paperqa/readers.py
Labels: bug, size:XS, lgtm

#476 Updating `test_tool_failure` cassette
  tests/cassettes/TestTaskDataset.test_tool_failure.yaml
Labels: bug, size:XS, lgtm

#477 Simplifying the indexing of `action` tokens
  paperqa/agents/env.py
  paperqa/types.py
Labels: enhancement, size:S, lgtm

#482 Fixing `tests/tests/cassettes` issue by using absolute path
  tests/conftest.py
Labels: bug, size:XS, lgtm

#479 Retrying on known Crossref flaky SSL error in `doi_to_bibtex`
  paperqa/clients/crossref.py
Labels: bug, size:S, lgtm

#483 Cleaning up and testing `get_directory_index`
  paperqa/agents/search.py
  tests/test_agents.py
Labels: enhancement, size:L, lgtm

#487 Modernizing Renovate config
  .github/renovate.json5
  .pre-commit-config.yaml
Labels: enhancement, size:S, lgtm

#491 Allowing `parse_text` to be given a `str` path
  paperqa/readers.py
Labels: enhancement, size:XS, lgtm

#489 Refactor to expose `agents.RichHandler`
  .pre-commit-config.yaml
  paperqa/agents/__init__.py
Labels: enhancement, size:L, lgtm

#493 Discovered Renovate `:automergeMinor` and preventing `openai` version bumps
  .github/renovate.json5
Labels: enhancement, size:S, lgtm

#494 Fixing `LitQATaskDataset` deserialization from config
  paperqa/agents/task.py
  tests/test_task.py
Labels: bug, size:M, lgtm

#497 Broken reader ut
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
  tests/test_paperqa.py
  uv.lock
Labels: bug, size:S, lgtm

#500 Fixing `LitQATaskDatasetcompute_trajectory_metrics` crash with bad status extraction
  paperqa/agents/task.py
Labels: bug, size:S, lgtm

#501 For autogenerated `Router` kwargs, specifying `timeout` of 60-sec
  paperqa/llms.py
Labels: bug, size:XS, lgtm

#503 Cleaning up #489's implementation
  paperqa/agents/__init__.py
  paperqa/settings.py
Labels: enhancement, size:S, lgtm

#509 Filtering two more `DeprecationWarning`s
  pyproject.toml
Labels: enhancement, size:XS, lgtm
