Repository Future-House/paper-qa, pull requests merged in 2024-11, with the labels that each got.

#658 Ability to zero-shot `gen_answer`
  .pre-commit-config.yaml
  paperqa/docs.py
  paperqa/settings.py
  pyproject.toml
  tests/test_task.py
  uv.lock
Labels: enhancement, size:M, lgtm

#660 Moving to `uv` dependency groups
  .pre-commit-config.yaml
  pyproject.toml
Labels: enhancement, size:M, lgtm

#666 Convert citation to formatted_citation usage where necessary
  paperqa/agents/helpers.py
  paperqa/core.py
  paperqa/docs.py
  paperqa/types.py
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
  tests/test_clients.py
  tests/test_paperqa.py
Labels: enhancement, size:L, lgtm

#668 Catch edge case where externalIds field is None
  paperqa/types.py
  tests/test_paperqa.py
Labels: bug, size:S, lgtm

#669 Made o1 temperature issue a warning, instead of valueerror
  paperqa/settings.py
  tests/test_configs.py
  uv.lock
Labels: bug, size:S, lgtm

#672 `fake` agent allowing timeouts or exceptions,
  paperqa/agents/main.py
Labels: enhancement, size:L, lgtm

#673 Optional `AnswerSetting.max_answer_attempts` to allow a new unsure branch
  paperqa/agents/env.py
  paperqa/agents/task.py
  paperqa/agents/tools.py
  paperqa/settings.py
  tests/test_task.py
Labels: enhancement, size:M, lgtm

#670 Made it so you do not die on invalid tool
  .pre-commit-config.yaml
  paperqa/agents/env.py
  pyproject.toml
  uv.lock
Labels: bug, size:S, lgtm

#674 Allowing latest `pydantic-settings` and regenerated cassettes
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  pyproject.toml
  tests/cassettes/TestLiteLLMModel.test_max_token_truncation[with-router].yaml
  tests/cassettes/TestLiteLLMModel.test_max_token_truncation[without-router].yaml
  tests/cassettes/TestLiteLLMModel.test_run_prompt[with-router].yaml
  tests/cassettes/TestLiteLLMModel.test_run_prompt[without-router].yaml
  tests/cassettes/TestTaskDataset.test_tool_failure.yaml
  tests/cassettes/test_arxiv_doi_is_used_when_available.yaml
  tests/cassettes/test_author_matching.yaml
  tests/cassettes/test_bad_dois.yaml
  tests/cassettes/test_bad_titles.yaml
  tests/cassettes/test_bulk_doi_search.yaml
  tests/cassettes/test_bulk_title_search.yaml
  tests/cassettes/test_crossref_journalquality_fields_filtering.yaml
  tests/cassettes/test_docs_lifecycle.yaml
  tests/cassettes/test_doi_search[paper_attributes0].yaml
  tests/cassettes/test_doi_search[paper_attributes1].yaml
  tests/cassettes/test_doi_search[paper_attributes2].yaml
  tests/cassettes/test_ensure_sequential_run.yaml
  tests/cassettes/test_ensure_sequential_run_early_stop.yaml
  tests/cassettes/test_minimal_fields_filtering.yaml
  tests/cassettes/test_odd_client_requests.yaml
  tests/cassettes/test_partly_embedded_texts[False].yaml
  tests/cassettes/test_partly_embedded_texts[True].yaml
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
  tests/cassettes/test_s2_only_fields_filtering.yaml
  tests/cassettes/test_title_search[paper_attributes0].yaml
  tests/cassettes/test_title_search[paper_attributes1].yaml
  tests/cassettes/test_title_search[paper_attributes2].yaml
  tests/test_clients.py
  uv.lock
Labels: enhancement, size:S, lgtm

#671 Empty tool calls leading to `done` condition
  paperqa/agents/env.py
  paperqa/agents/task.py
  paperqa/agents/tools.py
  paperqa/settings.py
  tests/test_agents.py
Labels: bug, enhancement, size:L, lgtm

#675 Changed it to be debug for source quality
  paperqa/types.py
Labels: size:XS, lgtm

#679 Deprecation cycle for `AgentSettings.should_pre_search`
  paperqa/configs/contracrow.json
  paperqa/configs/wikicrow.json
  paperqa/settings.py
Labels: bug, size:S, lgtm

#681 Moved agent prompts to `prompts.py`
  paperqa/prompts.py
  paperqa/settings.py
Labels: enhancement, size:M, lgtm

#680 Refactor to remove `skip_system` from `LLMModel.run_prompt`
  paperqa/agents/helpers.py
  paperqa/docs.py
  paperqa/llms.py
  tests/test_llms.py
  tests/test_paperqa.py
  tests/test_rate_limiter.py
Labels: enhancement, size:M, lgtm

#682 Resolving `evidence_detailed_citations` and `Answer` deprecations
  paperqa/configs/contracrow.json
  paperqa/configs/debug.json
  paperqa/configs/fast.json
  paperqa/configs/tier1_limits.json
  paperqa/configs/wikicrow.json
  paperqa/docs.py
  paperqa/prompts.py
  tests/test_agents.py
  tests/test_paperqa.py
Labels: bug, size:S, lgtm

#683 Fixed agent prompt names and contents after #681 mess up
  paperqa/prompts.py
  paperqa/settings.py
Labels: bug, size:S, lgtm

#685 Removed `tool_names` validation for `gen_answer` being present
  paperqa/agents/env.py
  paperqa/settings.py
  tests/test_agents.py
Labels: enhancement, size:M, lgtm

#691 Removed `GenerateAnswer.FAILED_TO_ANSWER` as its unnecessary
  paperqa/agents/env.py
  paperqa/agents/tools.py
  paperqa/types.py
  tests/test_agents.py
Labels: bug, size:M, lgtm

#688 Allowing serialized `Settings` in `get_settings`
  paperqa/settings.py
  tests/test_configs.py
Labels: enhancement, size:S, lgtm

#689 Removed `gen_answer`'s dead argument `question`
  paperqa/agents/main.py
  paperqa/agents/tools.py
  tests/test_agents.py
Labels: bug, size:M, lgtm

#694 Making sure we copy distractors
  paperqa/litqa.py
  tests/test_litqa.py
  uv.lock
Labels: bug, size:L, lgtm

#684 Created `complete` tool to allow unsure answers
  paperqa/agents/env.py
  paperqa/agents/task.py
  paperqa/agents/tools.py
  paperqa/configs/contracrow.json
  paperqa/configs/wikicrow.json
  paperqa/prompts.py
  tests/cassettes/TestTaskDataset.test_tool_failure.yaml
  tests/test_agents.py
Labels: enhancement, size:L, lgtm

#696 Added missing `test_from_question` cassette
  tests/cassettes/TestLitQAEvaluation.test_from_question.yaml
  tests/test_litqa.py
Labels: bug, size:XS, lgtm

#695 Moved `fake` agent to LLM propose `complete` tool
  paperqa/agents/helpers.py
  paperqa/agents/main.py
  paperqa/llms.py
Labels: enhancement, size:M, lgtm

#697 Default to ordered tool calls, w env variable control
  paperqa/agents/env.py
  tests/test_agents.py
Labels: bug, size:M, lgtm

#702 Refactored `TestGradablePaperQAEnvironment` for DRY code
  tests/test_agents.py
Labels: enhancement, size:L, lgtm

#703 Fixing `PaperQAEnvironment.reset` respecting `mmr_lambda` and `text_hashes`
  paperqa/docs.py
  paperqa/llms.py
  tests/test_task.py
Labels: bug, size:M, lgtm

#708 Fixing `LitQAEvaluation` bugs: incorrect reward indices, not using LLM's native knowledge
  paperqa/agents/task.py
  paperqa/litqa.py
  paperqa/prompts.py
  pyproject.toml
  tests/cassettes/TestLitQAEvaluation.test_from_question.yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[What is my office-s zip code--94107-distractors0-the answer is 94107-correct-expected_dreturns0].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[What is my office-s zip code--94107-distractors1-the answer is 14004-incorrect-expected_dreturns1].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[What is my office-s zip code--94107-distractors2-the answer is 94106-incorrect-expected_dreturns2].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[What is my office-s zip code--94107-distractors3-Insufficient information-unsure-expected_dreturns3].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[What is my office-s zip code--94107-distractors4-the answer is 94106 or 94107-incorrect-expected_dreturns4].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[What is the meaning of life--42-distractors5-14-incorrect-expected_dreturns5].yaml
  tests/test_litqa.py
  tests/test_task.py
Labels: bug, size:L, lgtm

#707 Adding filters to paper-qa Docs
  paperqa/docs.py
  paperqa/settings.py
  paperqa/types.py
  tests/test_configs.py
Labels: enhancement, size:L, lgtm

#711 Fixed mutably defaulted `NumpyVectorStore.texts`
  paperqa/llms.py
Labels: bug, size:XS, lgtm

#713 Fixed settings `session` into `EnvironmentState`, and suppressing PyMuPDF derived `DeprecationWarning`
  paperqa/agents/env.py
  paperqa/agents/tools.py
  pyproject.toml
  tests/test_agents.py
Labels: bug, size:S, lgtm

#716 Adding assertion `gather_evidence` doesn't populate `session.answer`
  tests/test_agents.py
Labels: enhancement, size:XS

#714 Fixes `gather_with_concurrency` typing
  .pre-commit-config.yaml
  paperqa/clients/__init__.py
  paperqa/docs.py
  paperqa/types.py
  paperqa/utils.py
  pyproject.toml
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
  uv.lock
Labels: size:M, lgtm

#724 Fixed `EVAL_PROMPT_TEMPLATE` to handle empty string or multiple match answers
  paperqa/prompts.py
  tests/cassettes/TestLitQAEvaluation.test_from_question[What is my office-s zip code--94107-distractors0-the answer is 94107-correct-expected_dreturns0].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[What is my office-s zip code--94107-distractors1-the answer is 14004-incorrect-expected_dreturns1].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[What is my office-s zip code--94107-distractors2-the answer is 94106-incorrect-expected_dreturns2].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[What is my office-s zip code--94107-distractors3-Insufficient information-unsure-expected_dreturns3].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[What is the meaning of life--42-distractors5-14-incorrect-expected_dreturns5].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[didnt-match-and-llm-has-innate-knowledge].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[didnt-match-and-no-llm-innate-knowledge].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[empty-answer1].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[empty-answer2].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[empty-answer3].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[matched-correct-option].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[matched-incorrect-option].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[matched-several-options].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[matched-unsure-option].yaml
  tests/test_litqa.py
Labels: bug, size:M, lgtm

#726 Address missing `GenerateAnswer` in trajectories, no answers after `Complete` tools, and better history
  paperqa/agents/env.py
  paperqa/agents/main.py
  paperqa/agents/tools.py
  paperqa/types.py
  tests/test_agents.py
Labels: bug, size:M, lgtm

#728 Pulling in latest `aviary` for `concurrency` rename
  .pre-commit-config.yaml
  paperqa/agents/env.py
  pyproject.toml
  uv.lock
Labels: enhancement, size:XS

#729 Pulling in latest `aviary` for dependencies fix, and retrying flaky `test_propagate_options` more
  .pre-commit-config.yaml
  pyproject.toml
  tests/test_agents.py
  uv.lock
Labels: bug, size:XS

#734 Pulling in latest `ldp` for `Callback.before_rollout`
  .pre-commit-config.yaml
  pyproject.toml
  tests/test_task.py
  uv.lock
Labels: enhancement, size:S, lgtm
