Repository Future-House/paper-qa, pull requests merged in 2025-03, with the labels that each got.

#894 Deferred `PQA_HOME` evaluation until `Settings` construction
  paperqa/settings.py
  tests/test_configs.py
Labels: bug, size:M, lgtm

#901 Added discussion to tutorial showing a dry setup for anthropic
  .pre-commit-config.yaml
  docs/tutorials/settings_tutorial.ipynb
  docs/tutorials/settings_tutorial.md
Labels: documentation, size:L, lgtm

#897 Lfrqa tutorial adjustments
  docs/tutorials/running_on_lfrqa.ipynb
  docs/tutorials/running_on_lfrqa.md
Labels: documentation, size:XL, lgtm

#903 Mentioned `dev` extra in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation, size:XS, lgtm

#907 Implemented `PaperQAEnvironment.from_task`
  paperqa/agents/env.py
  tests/test_agents.py
Labels: enhancement, size:M, lgtm

#911 Support for answer iterations in the gen_answer flow
  paperqa/docs.py
  paperqa/prompts.py
  paperqa/settings.py
  tests/test_paperqa.py
Labels: enhancement, size:M, lgtm

#912 Only show the top contexts to the agent for the specific question
  paperqa/agents/tools.py
  paperqa/core.py
  paperqa/types.py
  tests/test_agents.py
Labels: enhancement, size:M, lgtm

#916 Pulled in latest `tantivy` for `Document.from_dict` typing fix
  .pre-commit-config.yaml
  paperqa/agents/search.py
  pyproject.toml
  uv.lock
Labels: enhancement, size:XS, lgtm

#918 Catch retry errors, i.e. when a metadata service fails
  paperqa/clients/client_models.py
Labels: bug, size:XS, lgtm

#920 Pulling in Pydantic 2.11, latest tooling, doctests
  .pre-commit-config.yaml
  docs/tutorials/running_on_lfrqa.md
  docs/tutorials/settings_tutorial.md
  paperqa/types.py
  pyproject.toml
  uv.lock
Labels: enhancement, size:M, lgtm

#923 Removed LFRQA prompts
  paperqa/prompts.py
Labels: bug, size:M, lgtm

#922 Integrating `typos` tool
  .pre-commit-config.yaml
  paperqa/clients/semantic_scholar.py
  paperqa/docs.py
  paperqa/sources/clinical_trials.py
  pyproject.toml
  tests/test_clients.py
  tests/test_paperqa.py
Labels: bug, enhancement, size:M, lgtm

#926 Resolved a few deprecation warnings
  paperqa/clients/crossref.py
  paperqa/clients/semantic_scholar.py
  pyproject.toml
Labels: bug, size:XS, lgtm

#927 Fixed `README` typo on `basename`
  README.md
Labels: bug, documentation, size:XS, lgtm
