Repository Future-House/paper-qa, pull requests merged in 2025-02, with the labels that each got.

#846 Fixed pagination issue in search.py and added corresponding test
  paperqa/agents/search.py
  tests/test_agents.py
Labels: bug, size:S, lgtm

#836 Fixed mutable default issue in `is_hydration_needed`
  paperqa/types.py
Labels: bug, size:XS, lgtm

#842 Latest tooling and deps
  .pre-commit-config.yaml
  paperqa/agents/env.py
  paperqa/agents/tools.py
  paperqa/llms.py
  paperqa/settings.py
  paperqa/sources/clinical_trials.py
  paperqa/types.py
  paperqa/utils.py
  tests/test_clients.py
  tests/test_configs.py
  uv.lock
Labels: enhancement, size:M, lgtm

#847 Allow `agent_query` to Use an Existing Search Index Without Rebuilding
  paperqa/agents/main.py
  paperqa/settings.py
  tests/test_agents.py
Labels: enhancement, size:S

#849 Support parallel indexing
  paperqa/agents/search.py
  paperqa/docs.py
  paperqa/readers.py
  paperqa/settings.py
  pyproject.toml
  tests/test_agents.py
  tests/test_paperqa.py
Labels: enhancement, size:L, lgtm

#848 Added the get_manifest_kwargs function to get more than doi and title…
  paperqa/agents/search.py
  paperqa/clients/__init__.py
  paperqa/docs.py
  paperqa/sources/clinical_trials.py
  paperqa/types.py
  tests/stub_data/stub_manifest_nocitation.csv
  tests/test_agents.py
  tests/test_paperqa.py
Labels: enhancement, size:L, lgtm

#858 added escape_backlashes function with test
  paperqa/core.py
  tests/test_paperqa.py
Labels: enhancement, size:S, lgtm

#863 Fixing typing on `GradablePaperQAEnvironment` and `LFRQAPairwiseEvalEnv`'s evaluations
  .pre-commit-config.yaml
  paperqa/agents/task.py
  pyproject.toml
  uv.lock
Labels: enhancement, size:M

#853 Specific rag-qa-arena changes
  .gitignore
  .pre-commit-config.yaml
  docs/tutorials/running_on_lfrqa.md
  paperqa/agents/search.py
  paperqa/agents/task.py
  paperqa/prompts.py
  pyproject.toml
  uv.lock
Labels: documentation, size:XL, lgtm

#867 Corrected paper title in tutorial
  docs/tutorials/running_on_lfrqa.md
Labels: documentation, size:XS, lgtm

#843 Changes to llm_parse_json() to handle issues when LLM does not respond as per instructions
  paperqa/core.py
  tests/test_paperqa.py
Labels: bug, size:L, lgtm

#870 Correctly escape backlashes
  paperqa/core.py
  tests/test_paperqa.py
Labels: bug, size:S, lgtm

#872 Migrated LitQA and LFRQA to aviary
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  README.md
  paperqa/agents/task.py
  paperqa/litqa.py
  pyproject.toml
  tests/cassettes/TestLitQAEvaluation.test_from_question[didnt-match-and-llm-has-innate-knowledge].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[didnt-match-and-no-llm-innate-knowledge].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[empty-answer1].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[empty-answer2].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[empty-answer3].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[matched-correct-option].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[matched-incorrect-option].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[matched-several-options].yaml
  tests/cassettes/TestLitQAEvaluation.test_from_question[matched-unsure-option].yaml
  tests/cassettes/TestTaskDataset.test_tool_failure.yaml
  tests/test_agents.py
  tests/test_litqa.py
  tests/test_task.py
  uv.lock
Labels: documentation, enhancement, size:XXL, lgtm

#874 Fix aviary typing
  .pre-commit-config.yaml
  paperqa/agents/env.py
  pyproject.toml
  uv.lock
Labels: bug, size:XS, lgtm

#871 Add support and instructions for gemini
  .github/workflows/tests.yml
  README.md
  paperqa/agents/main.py
  paperqa/settings.py
  tests/test_agents.py
Labels: documentation, enhancement, size:M, lgtm

#875 Fixed flaky `test_answer_rename` via `flaky` decoration
  tests/test_paperqa.py
Labels: bug, size:XS, lgtm

#839 Propagates llmclient changes to pqa
  .mailmap
  .pre-commit-config.yaml
  paperqa/__init__.py
  paperqa/agents/env.py
  paperqa/agents/helpers.py
  paperqa/agents/models.py
  paperqa/agents/tools.py
  paperqa/clients/__init__.py
  paperqa/core.py
  paperqa/docs.py
  paperqa/llms.py
  paperqa/settings.py
  paperqa/sources/clinical_trials.py
  paperqa/types.py
  paperqa/utils.py
  pyproject.toml
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
  tests/test_agents.py
  tests/test_paperqa.py
  uv.lock
Labels: enhancement, size:L, lgtm

#880 Using API key and VCR constants defined in `lmi`
  tests/conftest.py
  tests/test_paperqa.py
Labels: size:XS, lgtm

#881 Supporting `.md` in indexing
  README.md
  paperqa/agents/search.py
  tests/stub_data/gravity_hill.md
  tests/test_agents.py
Labels: enhancement, size:M, lgtm

#883 Many minor updates to `README`
  README.md
  paperqa/settings.py
Labels: documentation, size:M

#879 Add openreview helper to fetch papers from conferences
  .mailmap
  CONTRIBUTING.md
  README.md
  docs/tutorials/where_do_I_get_papers.md
  paperqa/configs/openreview.json
  paperqa/contrib/openreview_paper_helper.py
  pyproject.toml
  uv.lock
Labels: enhancement, size:L, lgtm

#886 Update clinical trials setting to use proper tool name
  paperqa/configs/clinical_trials.json
Labels: size:XS, lgtm

#887 Little fix in import at LFRQA tutorial
  docs/tutorials/running_on_lfrqa.md
Labels: documentation, size:XS, lgtm

#888 Fixed problematic date parsing
  paperqa/types.py
  paperqa/utils.py
  tests/test_paperqa.py
Labels: bug, size:M, lgtm

#892 Support to parse nested quotes in JSONs during the summary step
  paperqa/core.py
  tests/test_agents.py
  tests/test_paperqa.py
Labels: enhancement, size:M, lgtm

#893 Added tutorial showing how to configure paperqa `Settings`
  .pre-commit-config.yaml
  docs/tutorials/settings_tutorial.ipynb
  docs/tutorials/settings_tutorial.md
Labels: documentation, size:XL, lgtm

#896 Add reasoning from LLMResult to PQASession
  .pre-commit-config.yaml
  paperqa/docs.py
  paperqa/types.py
  pyproject.toml
  tests/cassettes/test_get_reasoning[deepseek-reasoner].yaml
  tests/cassettes/test_get_reasoning[openrouter-deepseek].yaml
  tests/test_paperqa.py
  uv.lock
Labels: enhancement, size:M, lgtm

#895 Added embeddings to claude and gemine examples in the readme
  README.md
Labels: documentation, size:S, lgtm
