Repository Future-House/paper-qa, pull requests merged in 2025-07, with the labels that each got.

#982 Modernized CI
  .github/renovate.json5
  .pre-commit-config.yaml
  paperqa/core.py
  paperqa/docs.py
  paperqa/llms.py
  paperqa/utils.py
  pyproject.toml
  tests/test_agents.py
  tests/test_paperqa.py
  uv.lock
Labels: enhancement, size:M

#983 Allow extras to be kept in user output
  paperqa/types.py
  tests/test_agents.py
Labels: enhancement, size:XS, lgtm

#984 Refactor to expose PDF parsing settings
  README.md
  paperqa/agents/__init__.py
  paperqa/contrib/zotero.py
  paperqa/docs.py
  paperqa/readers.py
  paperqa/settings.py
  paperqa/types.py
  paperqa/utils.py
  tests/conftest.py
  tests/test_configs.py
  tests/test_paperqa.py
Labels: enhancement, size:L, lgtm

#989 Fixing missing `bibtex_source`, and created `BibTeXSource` enum
  paperqa/clients/crossref.py
  paperqa/clients/semantic_scholar.py
  paperqa/types.py
  tests/test_paperqa.py
Labels: bug, size:M, lgtm

#988 Implemented `Text.__eq__`
  paperqa/docs.py
  paperqa/types.py
  tests/test_paperqa.py
Labels: enhancement, size:S, lgtm

#990 Change contexts to use ids rather than text
  README.md
  paperqa/configs/contracrow.json
  paperqa/configs/wikicrow.json
  paperqa/docs.py
  paperqa/prompts.py
  paperqa/settings.py
  paperqa/types.py
  paperqa/utils.py
  tests/cassettes/test_get_reasoning[deepseek-reasoner].yaml
  tests/cassettes/test_get_reasoning[openrouter-deepseek].yaml
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
  tests/test_agents.py
  tests/test_paperqa.py
Labels: bug, enhancement, size:L, lgtm

#991 Moved `debug` config to use Claude 3 Haiku
  paperqa/configs/debug.json
  tests/test_paperqa.py
Labels: bug, enhancement, size:XS, lgtm

#996 Centralized `codespell` config and refreshed tooling/lock file versions
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: enhancement, size:S

#1000 Specifying `default=` in `AnswerSettings.answer_length`
  paperqa/settings.py
Labels: bug, size:XS, lgtm

#998 Denying empty text going to `citation_prompt`
  paperqa/docs.py
Labels: bug, size:XS, lgtm

#1002 Removed extraneous mention of 'relevance scores' from QA prompt template
  paperqa/prompts.py
  tests/cassettes/test_get_reasoning[deepseek-reasoner].yaml
  tests/cassettes/test_get_reasoning[openrouter-deepseek].yaml
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
Labels: bug, size:XS, lgtm

#1003 Exposing environment on-reset hook for `Docs` preparation
  paperqa/agents/env.py
Labels: enhancement, size:S, lgtm

#1004 Removed `reset_log_levels` fixture
  tests/conftest.py
  tests/test_clients.py
Labels: enhancement, size:M, lgtm

#1009 Fixed `Context` not always requiring a `call-arg` type ignore
  paperqa/types.py
  tests/test_agents.py
Labels: bug, size:S, lgtm

#1008 Fixed `DocDetails.pages` having leading/trailing whitespace
  paperqa/types.py
  tests/cassettes/test_doi_search[paper_attributes3].yaml
  tests/test_clients.py
Labels: bug, size:S, lgtm

#1010 Sorting `Doc.fields_to_overwrite_from_metadata` serialization
  paperqa/types.py
  pyproject.toml
Labels: enhancement, size:S, lgtm

#1011 Ensuring manifest deserialization works for non-primitive fields
  README.md
  paperqa/agents/search.py
  paperqa/types.py
  tests/test_paperqa.py
Labels: bug, documentation, size:M, lgtm

#1013 Removing leading/trailing newlines from `Context` creation prompt
  paperqa/core.py
Labels: enhancement, size:S, lgtm

#1015 Adding variable timeouts for clients
  paperqa/clients/crossref.py
  paperqa/clients/openalex.py
  paperqa/clients/semantic_scholar.py
Labels: enhancement, size:S, lgtm

#1016 Fixed `aiohttp.ClientOSError` crashing us
  paperqa/clients/client_models.py
  tests/test_clients.py
Labels: bug, size:S, lgtm

#1018 Fixed `_s2_get_with_retrying` multiple values issue
  paperqa/clients/semantic_scholar.py
Labels: bug, size:XS

#1024 Removed dead code `repopulate_doc_id_from_doi` from `DocDetails`
  src/paperqa/types.py
Labels: bug, size:XS, lgtm

#1027 Made `DeprecationWarning` on moved `Settings` more precise
  src/paperqa/settings.py
Labels: bug, enhancement, size:XS, lgtm

#1030 Open sourced test of `encode_id`
  tests/test_paperqa.py
Labels: enhancement, size:XS, lgtm

#1031 Expose answer evidence score cutoff as config
  README.md
  src/paperqa/docs.py
  src/paperqa/settings.py
Labels: enhancement, size:S, lgtm

#1032 Support grouping contexts by question in the final context
  README.md
  src/paperqa/docs.py
  src/paperqa/settings.py
  tests/test_paperqa.py
Labels: enhancement, size:L, lgtm

#1034 Journal quality fixes
  src/paperqa/clients/client_data/journal_quality.csv
  src/paperqa/clients/journal_quality.py
  tests/cassettes/test_tricky_journal_quality_results[10.1016-j.bbcan.2023.188947-1].yaml
  tests/cassettes/test_tricky_journal_quality_results[10.1016-j.semcdb.2016.08.024-1].yaml
  tests/cassettes/test_tricky_journal_quality_results[10.1038-s41598-018-27044-6-1].yaml
  tests/cassettes/test_tricky_journal_quality_results[10.1073-pnas.1205508109-3].yaml
  tests/cassettes/test_tricky_journal_quality_results[10.1146-annurev.pathol.4.110807.092311-2].yaml
  tests/cassettes/test_tricky_journal_quality_results[10.1186-1471-2148-11-4-2].yaml
  tests/test_clients.py
Labels: size:M, lgtm

#1033 Avoiding citation prompt hallucinating doi.org URLs
  src/paperqa/prompts.py
Labels: bug, size:XS, lgtm

#1037 Removed trailing whitespace from `summary_json_system_prompt`
  src/paperqa/prompts.py
  tests/cassettes/test_get_reasoning[deepseek-reasoner].yaml
  tests/cassettes/test_get_reasoning[openrouter-deepseek].yaml
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
Labels: bug, size:XS, lgtm

#1043 Fixed `test_agent_types` after Gemini 1.5 deprecation
  tests/test_agents.py
Labels: bug, size:XS, lgtm

#1042 Renamed a few more `answer` to `session`
  tests/test_paperqa.py
Labels: bug, size:S, lgtm
