Repository Future-House/paper-qa, pull requests merged in 2025-05, with the labels that each got.

#945 Pulled in latest `litellm` and `fhlmi`
  pyproject.toml
  tests/cassettes/test_get_reasoning[deepseek-reasoner].yaml
  tests/test_paperqa.py
  uv.lock
Labels: enhancement, size:S

#931 Moved Renovate config validation to CI
  .github/workflows/tests.yml
  .pre-commit-config.yaml
Labels: bug, size:XS

#946 Supporting Python 3.13
  .github/workflows/tests.yml
  .python-version
  pyproject.toml
  uv.lock
Labels: enhancement, size:XS, lgtm

#953 Usable "getting started" docs in `README`, both interpreter and Jupyter
  README.md
  paperqa/agents/__init__.py
  paperqa/utils.py
  tests/test_cli.py
Labels: documentation, enhancement, size:L, lgtm

#948 Add error handling for index file loading in SearchIndex
  paperqa/agents/search.py
Labels: bug, size:S
