Repository Future-House/paper-qa, pull requests merged in 2025-06, with the labels that each got.

#963 Fixing flaky `test_ensure_robust_to_timeouts` by lowering timeout by 10X
  tests/test_clients.py
Labels: bug, size:XS

#961 Fixing code chunking working with binary files
  .gitignore
  paperqa/readers.py
  paperqa/settings.py
  tests/stub_data/.DS_Store
  tests/test_agents.py
  tests/test_paperqa.py
Labels: bug, size:L, lgtm

#965 Fixed `chunk_code_text`'s `UnboundLocalError` crash on empty code file
  paperqa/readers.py
  tests/stub_data/py.typed
  tests/test_paperqa.py
Labels: bug, size:S, lgtm

#967 Added missing PyPI classifiers
  pyproject.toml
Labels: enhancement, size:XS

#972 add client response errors to our catching stack
  paperqa/clients/client_models.py
Labels: bug, size:XS, lgtm

#973 Making use of new `Environment.get_id`
  paperqa/agents/env.py
  pyproject.toml
  tests/test_agents.py
  uv.lock
Labels: enhancement, size:S, lgtm

#938 Fix pdf parsing bug
  README.md
  paperqa/docs.py
  paperqa/readers.py
  paperqa/settings.py
  tests/stub_data/pasa.pdf
  tests/test_agents.py
  tests/test_paperqa.py
Labels: bug, size:M, lgtm

#975 Fixed flaky test `test_chain_completion` via resolving `Cannot add callback`
  .pre-commit-config.yaml
  pyproject.toml
  tests/conftest.py
  uv.lock
Labels: bug, size:S

#977 Allow for non-mutated user specified doc-ids
  paperqa/clients/journal_quality.py
  paperqa/clients/retractions.py
  paperqa/types.py
  tests/test_paperqa.py
Labels: bug, size:L

#979 Rolling out `markdownlint-cli` to lint Markdown
  .pre-commit-config.yaml
  README.md
  pyproject.toml
Labels: documentation, enhancement, size:L
