Repository Future-House/paper-qa, pull requests merged in 2025-04, with the labels that each got.

#925 Began deprecation of non-`async` methods in `Docs`
  README.md
  docs/tutorials/where_do_I_get_papers.md
  paperqa/docs.py
  tests/test_paperqa.py
Labels: bug, documentation, enhancement, size:L, lgtm

#929 Gave instructions to correct citation on answer
  paperqa/prompts.py
  tests/cassettes/test_get_reasoning[deepseek-reasoner].yaml
  tests/cassettes/test_get_reasoning[openrouter-deepseek].yaml
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
  tests/test_agents.py
Labels: size:M, lgtm

#933 Pulled in latest `fhaviary` for tool schemae changes
  .pre-commit-config.yaml
  pyproject.toml
  tests/test_agents.py
  uv.lock
Labels: enhancement, size:S, lgtm

#936 Removed Gemini special case in `Settings.adjust_tools_for_agent_llm`
  paperqa/settings.py
Labels: enhancement, size:S, lgtm
