Repository Future-House/paper-qa, pull requests merged in 2025-09, with the labels that each got.

#1089 Context id updates
  src/paperqa/types.py
  src/paperqa/utils.py
  tests/test_paperqa.py
Labels: bug, size:L, lgtm

#1098 Adopting `prek` over `pre-commit`, `setup-uv`'s `python-version`
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: enhancement, size:S, lgtm

#1103 Gather evidence fails gracefully on timeout
  src/paperqa/core.py
  tests/test_paperqa.py
Labels: bug, size:L, lgtm

#1107 Minor prompt adjustments and docs
  src/paperqa/prompts.py
  tests/test_paperqa.py
Labels: documentation, enhancement, size:M, lgtm

#1108 Fixing tests after `0` score prompt change
  tests/cassettes/test_get_reasoning[deepseek-reasoner].yaml
  tests/cassettes/test_get_reasoning[openrouter-deepseek].yaml
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
  tests/test_paperqa.py
Labels: bug, size:S

#1109 Fixing `used_images` usage in `summary_json_system_prompt`
  README.md
  src/paperqa/prompts.py
  tests/test_paperqa.py
Labels: bug, size:S, lgtm

#1102 Removed `actions/setup-python` from `pre-commit`
  .github/workflows/tests.yml
Labels: bug, size:XS, lgtm

#1110 Newer `pre-commit` deps, to test `pre-commit` CI works
  .pre-commit-config.yaml
  src/paperqa/clients/__init__.py
  src/paperqa/clients/openalex.py
  src/paperqa/clients/unpaywall.py
  src/paperqa/types.py
  tests/cassettes/test_get_reasoning[deepseek-reasoner].yaml
  tests/cassettes/test_get_reasoning[openrouter-deepseek].yaml
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
Labels: enhancement, size:S

#1113 Dropping irrelevant contexts
  src/paperqa/agents/tools.py
  src/paperqa/docs.py
  tests/test_agents.py
  tests/test_paperqa.py
Labels: bug, enhancement, size:M, lgtm
