Repository Future-House/paper-qa, pull requests merged in 2025-01, with the labels that each got.

#777 Add clinical trials search tool
  paperqa/agents/env.py
  paperqa/agents/helpers.py
  paperqa/agents/tools.py
  paperqa/clients/__init__.py
  paperqa/clients/crossref.py
  paperqa/clients/journal_quality.py
  paperqa/clients/openalex.py
  paperqa/clients/retractions.py
  paperqa/clients/semantic_scholar.py
  paperqa/clients/unpaywall.py
  paperqa/llms.py
  paperqa/settings.py
  paperqa/sources/__init__.py
  paperqa/sources/clinical_trials.py
  pyproject.toml
  tests/test_agents.py
  tests/test_clinical_trials.py
  tests/test_paperqa.py
Labels: enhancement, size:XXL, lgtm

#785 Replace `raise_for_status` return `None` with Mock() in clinical trials test
  tests/test_clinical_trials.py
Labels: bug, size:XS, lgtm

#768 Moved to `MultipleChoiceQuestion`/`MultipleChoiceEvaluation` from `aviary`
  .pre-commit-config.yaml
  paperqa/_ldp_shims.py
  paperqa/agents/env.py
  paperqa/agents/models.py
  paperqa/agents/task.py
  paperqa/litqa.py
  paperqa/types.py
  pyproject.toml
  tests/test_litqa.py
  tests/test_task.py
  uv.lock
Labels: enhancement, size:XL, lgtm

#776 Feat/qdrant docs reconstruct
  paperqa/llms.py
  tests/test_paperqa.py
Labels: enhancement, size:L, lgtm

#788 Removed dead test cassettes
  tests/cassettes/TestLiteLLMModel.test_max_token_truncation[with-router].yaml
  tests/cassettes/TestLiteLLMModel.test_max_token_truncation[without-router].yaml
  tests/cassettes/TestLiteLLMModel.test_run_prompt[with-router].yaml
  tests/cassettes/TestLiteLLMModel.test_run_prompt[without-router].yaml
Labels: bug, size:XS

#790 Pinning min version of `fh-llm-client`
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: bug, size:XS, lgtm

#791 Fixed `Record` import from Qdrant not being in `TYPE_CHECKING` block
  paperqa/llms.py
Labels: bug, size:S, lgtm

#792 Fixing not using `set_llm_session_ids` from `fh-llm-client`
  paperqa/docs.py
  paperqa/types.py
  tests/test_paperqa.py
Labels: bug, size:M, lgtm

#793 Expose more contexts as output from gather_evidence tool
  paperqa/agents/tools.py
  paperqa/settings.py
  tests/test_agents.py
Labels: enhancement, size:M, lgtm

#795 `Settings` lookup table and improved `Settings` descriptions
  README.md
  paperqa/settings.py
Labels: documentation, size:L

#797 Fixing incorrect seeding argument due to Pydantic `extra="ignore"`
  tests/test_task.py
Labels: bug, size:S

#798 Loosened input types to allow more `MultipleChoiceQuestion`
  paperqa/agents/__init__.py
  paperqa/agents/main.py
Labels: enhancement, size:S

#800 Added `aviary-paper-data` as LitQA v2 test split
  .github/workflows/tests.yml
  paperqa/agents/task.py
  paperqa/litqa.py
  tests/test_litqa.py
  tests/test_task.py
Labels: enhancement, size:M, lgtm

#802 Added `LitQAv2TaskSplit.get_index` convenience
  paperqa/agents/task.py
  tests/test_task.py
Labels: enhancement, size:M, lgtm

#799 Refactor to remove `QueryRequest` entity
  README.md
  paperqa/__init__.py
  paperqa/agents/__init__.py
  paperqa/agents/env.py
  paperqa/agents/main.py
  paperqa/agents/models.py
  paperqa/agents/task.py
  tests/test_agents.py
  tests/test_task.py
Labels: enhancement, size:L, lgtm

#804 Latest tooling
  .pre-commit-config.yaml
  paperqa/agents/search.py
  paperqa/clients/openalex.py
  pyproject.toml
  tests/test_agents.py
  tests/test_clients.py
Labels: enhancement, size:M, lgtm

#808 Fixing tool failures crashing runners in failover answer
  paperqa/agents/main.py
Labels: bug, size:XS, lgtm

#809 Fixing evidence counted in `gather_evidence`'s response message
  paperqa/agents/tools.py
Labels: bug, size:S, lgtm

#801 Ensure fields are lists before combining in DocDetails class
  .mailmap
  paperqa/types.py
  tests/test_paperqa.py
Labels: size:M, lgtm

#810 Pulling in latest `fh-llm-client` for `CommonLLMNames`
  .pre-commit-config.yaml
  paperqa/settings.py
  pyproject.toml
  tests/cassettes/TestTaskDataset.test_tool_failure.yaml
  tests/cassettes/test_docs_lifecycle.yaml
  tests/cassettes/test_partitioning_fn_docs[False].yaml
  tests/cassettes/test_partitioning_fn_docs[True].yaml
  tests/cassettes/test_partly_embedded_texts[False].yaml
  tests/cassettes/test_partly_embedded_texts[True].yaml
  tests/cassettes/test_pdf_reader_match_doc_details.yaml
  tests/test_agents.py
  tests/test_paperqa.py
  uv.lock
Labels: enhancement, size:S

#812 Fixing `gather_evidence` and `complete` response messages
  paperqa/agents/env.py
  paperqa/agents/tools.py
  tests/test_agents.py
Labels: bug, size:M, lgtm

#813 Resolving typing PR comments
  paperqa/agents/helpers.py
  paperqa/types.py
  tests/test_paperqa.py
Labels: enhancement, size:M, lgtm

#770 Fixed type problems from llmclient
  paperqa/agents/helpers.py
  paperqa/agents/search.py
  paperqa/clients/crossref.py
  paperqa/clients/journal_quality.py
  paperqa/clients/openalex.py
  paperqa/clients/retractions.py
  paperqa/clients/semantic_scholar.py
  paperqa/clients/unpaywall.py
  paperqa/core.py
  paperqa/docs.py
  paperqa/readers.py
  paperqa/types.py
  tests/test_cli.py
  tests/test_paperqa.py
Labels: size:L, lgtm

#819 Clinical trials docs and bugfixes
  docs/tutorials/querying_with_clinical_trials.md
  paperqa/agents/main.py
  paperqa/configs/clinical_trials.json
  paperqa/configs/search_only_clinical_trials.json
  paperqa/sources/clinical_trials.py
  paperqa/utils.py
Labels: bug, documentation, size:L

#816 Fixing flaky test `test_cli_can_build_and_search_index` by retrying
  tests/test_cli.py
Labels: bug, size:S

#818 Allowing more general types in `Settings`
  paperqa/core.py
  paperqa/docs.py
  paperqa/llms.py
  paperqa/settings.py
  paperqa/types.py
  tests/test_agents.py
Labels: enhancement, size:M

#817 Documenting citation style
  paperqa/docs.py
  paperqa/settings.py
  paperqa/utils.py
Labels: documentation, enhancement, size:M, lgtm

#821 Updated badges in README
  README.md
Labels: documentation, size:XS, lgtm

#826 Pulling in latest `ldp` for `bulk_evaluate_consensus`
  .pre-commit-config.yaml
  paperqa/_ldp_shims.py
  paperqa/agents/task.py
  pyproject.toml
  uv.lock
Labels: enhancement, size:S, lgtm

#824 Updated `CITATION.cff` to include more info
  CITATION.cff
Labels: documentation, enhancement, size:XS

#827 Pulled in latest `fh-llm-client` to resolve `TODO` on `callbacks` cast
  .pre-commit-config.yaml
  paperqa/docs.py
  pyproject.toml
  uv.lock
Labels: enhancement, size:S, lgtm

#828 Automate fetching the current year
  paperqa/prompts.py
  tests/test_configs.py
  uv.lock
Labels: enhancement, size:S, lgtm

#834 Fixed typo in pip install instructions
  README.md
Labels: documentation, size:XS, lgtm
